### ISSUE TITLE
[Feature] Vérifier le status des vérifications GitHub du tag avant déploiement

### ISSUE THREAD

**Issue by HEYGUL** [1024pix/pix-bot#15]
## :unicorn: Problème
La CI est lancée à chaque commit sur `dev`.
Actuellement, si le workflow déclenché par ce commit échoue, nous n'avons aucun retour lors de la mise en production, bien que celle-ci soit bloquée.
Lors de la création / publication de la release, nous ne faisons aucune vérification de l'état du workflow. Ainsi, il est possible d'indiquer que la release se soit correctement déroulée alors que la CI soit en échec.

## :robot: Solution
GitHub offre une API permettant de récupérer l'état des vérifications (checks) d'un tag.
On utilise l'API pour :

-  vérifier l'état de la CI **avant** le déploiement d'une release sur Production
-  attendre la CI **après** création de la release (mais **avant** son déploiement sur Recette)

Un message d'erreur sur Slack est posté en cas d'échec de la CI liée à la création / déploiement d'une release.

**Comment by francois2metz** [comment]
Fait par #36
