### ISSUE TITLE
Trop de `scale` simultanés provoquent des échecs

### ISSUE THREAD

**Issue by jonathanperret** [1024pix/pix-bot#4]
Ce matin, comme chaque matin, `pix-bot` a essayé de démarrer simultanément toutes les _review apps_ existantes.

Mais un certain nombre de ces applications n'ont pas démarré. En regardant l'historique des opérations sur les applications Scalingo (`scalingo timeline`) on voit pourtant bien une opération de `scale` qui a eu lieu.

Après investigation côté Scalingo :

> L'action scale  renvoie une ContainersOperation:
> ```
>    async scale(
>    appId: string,
>    formation: Container[],
>  ): Promise<ContainersOperation | APIError>
> ```
> Une opération a un status: https://developers.scalingo.com/operations.html qui est mis à jour.
> De mon analyse certainent échouent car vous lancer trop d'opérations de scaling en parallèle pour votre quotas. Ce que je propos et que vous fassiez du polling sur l'Operation avant de relancer une autre opération de scaling. Ainsi vous serez sûr que tout a redémarré  correctement.
-- Léo Unbekandt, Scalingo

Il semblerait donc qu'il faudrait surveiller les opérations de `scale` et ne pas toutes les lancer simultanément.

**Comment by jbuget** [comment]
Pix Bot utilise une dépendance - [scalingo-review-app-manager](https://github.com/1024pix/scalingo-review-app-manager) (développée par nos soins). Je pense que c'est sur ce projet qu'il faut déclarer l'issue. Et ensuite monter de version dans cette issue.
